server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    username: 'admin'
    password: 'password'
    url: jdbc:postgresql://postgresnotification:5432/postgres
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      show-sql: 'true'
  zipkin:
    base-url: http://zipkin:9411
  flyway:
    locations: classpath:db/migration
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key